export const actionTypes = {
    DESPESAS: 'DESPESAS',
    DELETE_DESPESA: 'DELETE_DESPESA',
    CREATE_DESPESA: 'CREATE_DESPESA',
    UPDATE_DESPESA: 'UPDATE_DESPESA',
    SET_DESPESA: 'SET_DESPESA',
    CHANGE_DESPESA: 'CHANGE_DESPESA',
    SEARCH_FILTER: 'SEARCH_FILTER'
}